### ISSUE TITLE
TwisterOS 

### ISSUE THREAD

**Issue by ghost** [ksharindam/xfce4-pi-volume-plugin#1]
Hi!! I am Salvador from twisterOS. We are trying to ditch pulseaudio bc it's creating severe problems with bt devices
and even then without them on other games (distortion).

site: www.twisteros.com
twister OS it's not just a theme based RPI OS, it's an xfce build with themes to allow to use BOX86 emulator easily
on RPI 4.

concerns: 
this is just a volume app only ?
we would like to have a dummy way to select different output devices.
but alsamixer seems no not be able to switch hmdi to jack, and doesn't show Bluetooth devices neither when paired as sound outputs.

so far I have the deps installed and the make file wont recognize my gtk (it doesn't find the include gtk files)

volumealsa.c:52:10: fatal error: gtk/gtk.h: No such file or directory

hope you collaborate here!! thanks buddy!!

**Comment by ksharindam** [comment]
Yes it is volume plugin only.
It is same as lxpanel volume plugin in RPi os. That means you can select
audio output to hdmi, 3.5mm jack or bluetooth device in this plugin.
If your os is based on RPi Os buster, then it should work.

Now, show me the output of the command...
`pkg-config --cflags --libs libxfce4panel-1.0 alsa`

**Comment by ghost** [comment]
yeah, you need to bump the version to libxfce4panel-2.0-4
it will brake too many stuff going old versions (it's not available on my buster rpi os)

**Comment by ksharindam** [comment]
I am currently using RPi Os buster , developing all programs using this os. So I can assure that all those build dependencies I mentioned in the README.md file, are available in rpi buster. 
I am afraid that you are not installing all the dependencies I mentioned. Please install all those dependencies.

As long as I use Buster, I dont need to bump the version. Because xfce4 panel supports both xfce4 panel api 1.0 and 2.0.
bumping to version 2.0 will create problem in maintainance, and produce many bugs.

**Comment by ksharindam** [comment]
@Askmewho if you dont show output of the terminal, i can not understand the problem and can't help you.
So closing this issue.
